name: "Test"

on:
  pull_request:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v13
      with:
        name: rosuavio-personal
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --run "echo OK"
    - run: nix-build -A vm
    - run: nix-build test
