name: update-nixpkgs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  niv-update:
    runs-on: ubuntu-latest
    steps:
    - name: Get date
      run: echo "BRANCH_NAME=nixpkgs-update-$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
    - uses: cachix/cachix-action@v12
      with:
        name: rosuavio-personal
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: git checkout -b $BRANCH_NAME
    - run: nix-shell --run "niv update nixpkgs"
    - run: git commit -am "Update nixpkgs"
    - run: git push -u origin $BRANCH_NAME
    - name: create pull request
      run: gh pr create -B main -H $BRANCH_NAME --title "Update nixpkgs" --body "Update nixpkgs"
